export const listOfSkills = [
  {
    key: 'HTML5',
    name: 'HTML5',
    type: 'Programming',
    value: 100,
  },
  {
    key: 'CSS3',
    name: 'CSS3',
    type: 'Programming',
    value: 95,
  },
  {
    key: 'JavaScript',
    name: 'JavaScript',
    type: 'Programming',
    value: 85,
  },
  {
    key: 'React',
    name: 'React',
    type: 'Programming',
    value: 75,
  },
  {
    key: 'Vue.js',
    name: 'Vue.js',
    type: 'Programming',
    value: 50,
  },
  {
    key: 'Next.js',
    name: 'Next.js',
    type: 'Programming',
    value: 26,
  },
  {
    key: 'Node.js',
    name: 'Node.js',
    type: 'Programming',
    value: 31,
  },
  {
    key: 'jQuery',
    name: 'jQuery',
    type: 'Programming',
    value: 42,
  },
  {
    key: 'Bulma.io',
    name: 'Bulma.io',
    type: 'Programming',
    value: 80,
  },
  {
    key: 'Bootstrap',
    name: 'Bootstrap',
    type: 'Programming',
    value: 50,
  },

  {
    key: 'PHP',
    name: 'PHP',
    type: 'Programming',
    value: 58,
  },
  {
    key: 'MySQL',
    name: 'MySQL',
    type: 'Programming',
    value: 54,
  },
  {
    key: 'C',
    name: 'C',
    type: 'Programming',
    value: 40,
  },

  {
    key: 'Git',
    name: 'Git',
    type: 'Programming',
    value: 90,
  },
  {
    key: 'English',
    name: 'English',
    type: 'Languages',
    value: 90,
  },
  {
    key: 'Portuguese',
    name: 'Portuguese',
    type: 'Languages',
    value: 99,
  },
  {
    key: 'Spanish',
    name: 'Spanish',
    type: 'Languages',
    value: 60,
  },
  {
    key: 'Mandarin',
    name: 'Mandarin',
    type: 'Languages',
    value: 50,
  },
  {
    key: 'Teamwork',
    name: 'Teamwork',
    type: 'Skills',
    value: 87,
  },
  {
    key: 'Time management',
    name: 'Time management',
    type: 'Skills',
    value: 95,
  },
  {
    key: 'Agile and Scrum',
    name: 'Agile and Scrum',
    type: 'Skills',
    value: 92,
  },
  {
    key: 'Leadership',
    name: 'Leadership',
    type: 'Skills',
    value: 79,
  },
  {
    key: 'Critical thinking',
    name: 'Critical thinking',
    type: 'Skills',
    value: 84,
  },
  {
    key: 'Delegation',
    name: 'Delegation',
    type: 'Skills',
    value: 92,
  },
];
